<script setup>
import {computed,ref,onMounted,onBeforeUnmount,watch,nextTick} from 'vue'
import MicroGridImage from './MicroGridImage.vue'
import {archive,shared} from '../composables/useArchive'
const props=defineProps({object:Object});const emit=defineEmits(['close','release']);const panel=ref(null)
const related=computed(()=>props.object.relatedIds.map(id=>archive.find(o=>o.id===id)).filter(Boolean))
const previous=document.activeElement
function key(e){if(e.key==='Escape')emit('close');if(e.key==='Tab'){const nodes=[...panel.value.querySelectorAll('button,a[href],summary')].filter(n=>n.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
onMounted(()=>{document.body.style.overflow='hidden';document.addEventListener('keydown',key);panel.value.querySelector('button').focus()})
onBeforeUnmount(()=>{document.body.style.overflow='';document.removeEventListener('keydown',key);previous?.focus()})
watch(()=>props.object.id,async()=>{await nextTick();panel.value.scrollTop=0})
</script>
<template><div class="detail-backdrop" @click.self="$emit('close')"><section class="detail-panel" ref="panel" role="dialog" aria-modal="true" aria-labelledby="detail-title"><header class="detail-header mono"><span>RELEASE / 展开原物</span><button @click="$emit('close')">× / RECYCLE 回流</button></header><div class="detail-layout"><div class="detail-visual"><MicroGridImage :object="object" original eager/><p class="mono">{{object.id}} · 原始图像 / ORIGINAL IMAGE</p></div><article><p class="mono">ARCHIVE {{object.id}} / {{'ABCDEF'[object.positionNumber-1]}}</p><h2 id="detail-title">{{object.title||object.id}}</h2><p v-if="object.placeAndPeriod" class="detail-period">{{object.placeAndPeriod}}</p><p class="detail-description">{{object.description}}</p><dl><template v-if="object.curatorialPosition"><dt>POSITION / 策展位置</dt><dd>{{object.curatorialPosition}}</dd></template><template v-if="object.sourceType.length"><dt>SOURCE TYPE / 来源类型</dt><dd>{{object.sourceType.join(' / ')}}</dd></template><template v-if="object.actions.length"><dt>ACTION CHAIN / 动作链</dt><dd>{{object.actions.join(' → ')}}</dd></template><template v-if="object.keywords.length"><dt>KEYWORDS / 关键词</dt><dd>{{object.keywords.join(' / ')}}</dd></template><template v-if="object.sourceTitle"><dt>SOURCE / REFERENCE / 出处</dt><dd>{{object.sourceTitle}}</dd></template><template v-if="object.url"><dt>SOURCE LINK / 来源链接</dt><dd><a :href="object.url" target="_blank" rel="noopener noreferrer">查看原表出处 ↗</a></dd></template></dl><div v-if="object.dataNotes.length" class="data-note"><p v-for="note in object.dataNotes" :key="note">{{note}}</p></div><details v-if="object.excelRow" class="raw-data"><summary>ORIGINAL RECORD / 原始 Excel 行 · {{object.excelRow}}</summary><dl><template v-for="(value,key) in object.rawRow" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template></dl></details></article></div><section class="related"><h3 class="mono">RELATED OBJECTS / 关系回流</h3><button v-for="o in related" :key="o.id" @click="$emit('release',o)"><span class="mono">{{o.id}}</span><strong>{{o.title||o.id}}</strong><small>{{shared(object,o)}}</small><span>↗</span></button></section></section></div></template>
