<script setup>
import {computed,ref,onMounted,onBeforeUnmount,nextTick,watch} from 'vue'
import translations from '../data/keywordTranslations.json'
import ArchiveCard from './ArchiveCard.vue'
const props=defineProps({objects:Array});defineEmits(['release'])
const selected=ref(''),dialog=ref(null);let previous=null
const terms=computed(()=>{const map=new Map();for(const o of props.objects)for(const k of new Set(o.keywords)){if(!map.has(k))map.set(k,{word:k,en:translations[k]||k,count:0,image:o.thumbnail||o.image});map.get(k).count++}return [...map.values()].sort((a,b)=>b.count-a.count||a.word.localeCompare(b.word,'zh-CN'))})
const bands=computed(()=>{const groups=[];for(const term of terms.value){let last=groups.at(-1);if(!last||last.count!==term.count){last={count:term.count,terms:[]};groups.push(last)}last.terms.push(term)}return groups})
const matches=computed(()=>props.objects.filter(o=>o.keywords.includes(selected.value)))
function size(count){const max=terms.value[0]?.count||1;return max===1?24:22+62*(Math.log(count)/Math.log(max))}
async function open(word){previous=document.activeElement;selected.value=word;await nextTick();dialog.value?.querySelector('button').focus()}
function close(){selected.value='';previous?.focus()}
function key(e){if(!selected.value)return;if(e.key==='Escape'){e.stopImmediatePropagation();close()}if(e.key==='Tab'){const nodes=[...dialog.value.querySelectorAll('button,a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
onMounted(()=>document.addEventListener('keydown',key));onBeforeUnmount(()=>document.removeEventListener('keydown',key));watch(()=>props.objects,()=>selected.value='')
</script>
<template><section class="keyword-flow"><header class="flow-heading"><p>KEYWORD CURRENT / 关键词流</p><span>{{terms.length}} WORDS / 个关键词</span></header><p class="flow-description">按关联案例数排列。词越常见，越大、越靠上；点击查看当前范围内的全部关联案例。</p><div v-if="!terms.length" class="flow-empty">当前图像尚未标注关键词。<small>NO KEYWORDS IN THIS SELECTION.</small></div><div class="frequency-bands"><div v-for="band in bands" :key="band.count" class="frequency-band" :data-count="band.count"><button v-for="(term,i) in band.terms" :key="term.word" class="flow-word" :data-word="term.word" :data-count="term.count" :style="{'--word-size':size(term.count)+'px','--flow-delay':`${-i*1.7}s`}" @click="open(term.word)" :aria-label="`${term.word} / ${term.en}，${term.count} 个案例`"><span class="word-cn">{{term.word}}</span><span class="word-en">{{term.en}}</span><span class="word-mark"><sup>({{term.count}})</sup><img :src="term.image" alt="" loading="lazy"/></span></button></div></div><Teleport to="body"><div v-if="selected" class="keyword-backdrop" @click.self="close"><section ref="dialog" class="keyword-dialog" role="dialog" aria-modal="true" aria-labelledby="keyword-title"><header><div><p class="mono">KEYWORD / 关键词</p><h2 id="keyword-title">{{selected}} <span>{{translations[selected]||selected}}</span></h2><p>{{matches.length}} OBJECTS / 个关联案例</p></div><button @click="close">× 返回词流 / BACK</button></header><div class="keyword-cards"><ArchiveCard v-for="o in matches" :key="o.id" :object="o" @release="close();$emit('release',$event)"/></div></section></div></Teleport></section></template>
