<script setup>
import {ref,onMounted,onBeforeUnmount,watch} from 'vue'
import * as THREE from 'three'
import {OrbitControls} from 'three/addons/controls/OrbitControls.js'
const props=defineProps({objects:Array,level:Number,paused:Boolean});const emit=defineEmits(['release','fallback'])
const host=ref(null),error=ref(false),loading=ref(true),engaged=ref(false),hovered=ref(null)
let renderer,scene,camera,controls,frame,observer,resizeObserver,visible=false,disposed=false,group,core,raycaster,pointer,down,cleanups=[]
const cardLimit=ref(innerWidth<700?18:42)
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches
function zoom(f){if(!camera)return;camera.position.multiplyScalar(f);camera.position.setLength(THREE.MathUtils.clamp(camera.position.length(),9,35));controls.update();render()}
function render(){if(renderer&&scene&&camera)renderer.render(scene,camera)}
function start(){cancelAnimationFrame(frame);const tick=()=>{if(disposed||!visible)return;if(!props.paused){if(!reduced&&!hovered.value){group.rotation.y+=0.00045;core.rotation.y-=0.0007}controls.update();const localCamera=group.worldToLocal(camera.position.clone());group.children.forEach(m=>m.lookAt(localCamera));render()}frame=requestAnimationFrame(tick)};tick()}
function clearCards(){if(!group)return;for(const m of [...group.children]){group.remove(m);m.geometry.dispose();m.material.map?.dispose();m.material.dispose()}}
function populate(){if(!group)return;clearCards();const selected=props.objects.slice(0,cardLimit.value);selected.forEach((o,i)=>{const canvas=document.createElement('canvas');canvas.width=512;canvas.height=360;const ctx=canvas.getContext('2d');ctx.fillStyle='#f3f3ed';ctx.fillRect(0,0,512,360);ctx.fillStyle='#123deb';ctx.font='20px monospace';ctx.fillText(o.id,16,28);ctx.font='22px sans-serif';ctx.fillText(o.title.slice(0,30),16,326);ctx.font='14px monospace';ctx.fillText(o.actions.join(' > ').slice(0,55),16,349);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(2.8,1.97),material);const ring=Math.floor(i/14),angle=(i%14)/14*Math.PI*2+ring*0.19;mesh.position.set(Math.sin(angle)*7,(ring-1)*3.1,Math.cos(angle)*7);mesh.lookAt(0,mesh.position.y,0);mesh.userData.object=o;group.add(mesh);if(o.encodedImage){const img=new Image();img.onload=()=>{if(disposed||!group.children.includes(mesh))return;ctx.drawImage(img,16,45,480,253);texture.needsUpdate=true;render()};img.src=o.encodedImage}else{ctx.font='22px monospace';ctx.fillText('IMAGE NOT RETRIEVED',24,180);texture.needsUpdate=true}});render()}
onMounted(()=>{try{scene=new THREE.Scene();scene.background=new THREE.Color('#f3f3ed');scene.fog=new THREE.Fog('#f3f3ed',23,45);camera=new THREE.PerspectiveCamera(42,1,0.1,100);camera.position.set(0,5,23);renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));host.value.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','三维圆柱档案，拖动环绕；使用二维视图阅读全部档案');controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.enableZoom=false;controls.enablePan=false;controls.minDistance=9;controls.maxDistance=35;controls.maxPolarAngle=Math.PI*.8;controls.minPolarAngle=Math.PI*.2;
group=new THREE.Group();scene.add(group);const points=[];for(let i=0;i<1800;i++){const y=1-(i/1799)*2;const r=Math.sqrt(1-y*y);const t=i*2.39996;points.push(Math.cos(t)*r*2.45,y*2.45,Math.sin(t)*r*2.45)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(points,3));core=new THREE.Points(geo,new THREE.PointsMaterial({color:'#123deb',size:.115,sizeAttenuation:true}));scene.add(core);const circle=new THREE.Mesh(new THREE.RingGeometry(2.6,2.62,96),new THREE.MeshBasicMaterial({color:'#123deb',side:THREE.DoubleSide}));circle.rotation.x=Math.PI/2;scene.add(circle);const axes=new THREE.GridHelper(22,22,'#123deb','#d8dfeb');axes.position.y=-5;scene.add(axes);raycaster=new THREE.Raycaster();pointer=new THREE.Vector2();populate();
const move=e=>{const b=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(group.children)[0];hovered.value=hit?.object.userData.object||null;group.children.forEach(m=>m.scale.setScalar(m===hit?.object?1.055:1));renderer.domElement.style.cursor=hit?'pointer':'grab'};const pd=e=>{down=[e.clientX,e.clientY]};const pu=e=>{if(down&&Math.hypot(e.clientX-down[0],e.clientY-down[1])<5&&hovered.value)emit('release',hovered.value);down=null};for(const [event,fn] of [['pointermove',move],['pointerdown',pd],['pointerup',pu]]){renderer.domElement.addEventListener(event,fn);cleanups.push(()=>renderer.domElement.removeEventListener(event,fn))}
resizeObserver=new ResizeObserver(()=>{const w=host.value.clientWidth,h=host.value.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();render()});resizeObserver.observe(host.value);observer=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible)start();else cancelAnimationFrame(frame)});observer.observe(host.value);loading.value=false;
}catch(e){error.value=true;loading.value=false;console.warn('DEPTH unavailable; 2D archive remains available',e)}})
watch(()=>props.objects,populate);watch(engaged,v=>{if(controls)controls.enableZoom=v});watch(()=>props.level,l=>{if(core){const scale=.75+Math.min(l,100)/400;core.scale.setScalar(scale);render()}})
onBeforeUnmount(()=>{disposed=true;cancelAnimationFrame(frame);observer?.disconnect();resizeObserver?.disconnect();cleanups.forEach(f=>f());controls?.dispose();scene?.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose()});renderer?.dispose();renderer?.domElement.remove()})
</script>
<template><div class="orbital-shell" @keydown.up.prevent="zoom(.93)" @keydown.down.prevent="zoom(1.07)"><div class="orbital-top mono"><span>ORBITAL RESERVOIR ARCHIVE</span><span>{{Math.min(objects.length,cardLimit)}} / {{objects.length}} OBJECTS / LEVEL {{Math.round(level)}}%</span></div><div ref="host" class="orbital-canvas" tabindex="0"><p v-if="loading" class="orbital-loading mono">LOADING DEPTH DATA</p><p v-if="error" class="orbital-loading">三维不可用，档案仍可在二维视图中阅读。<button @click="$emit('fallback')">OPEN 2D ARCHIVE ↗</button></p></div><span v-if="!error" class="core-label mono">RESERVOIR<br><small>CORE / {{Math.round(level)}}%</small></span><div class="orbital-hover" v-if="hovered"><span class="mono">{{hovered.id}} / RELEASE ↗</span><strong>{{hovered.title}}</strong><small>{{hovered.placeAndPeriod}}</small><small>{{hovered.actions.join(' → ')}}</small></div><div class="orbital-controls mono"><span>DRAG TO ORBIT</span><button @click="zoom(.85)" aria-label="向前缩放">＋</button><button @click="zoom(1.15)" aria-label="向后缩放">−</button><button @click="engaged=!engaged" :aria-pressed="engaged">WHEEL {{engaged?'ON':'OFF'}}</button><button @click="$emit('fallback')">2D ↗</button></div></div></template>
